import {KEY, localDate, uid, fresh, validate, revise, planMerge, resolveMerge, periodRange, shiftDate, activeRecords, inRange, groups, validDate} from './model.js';
const $=s=>document.querySelector(s);
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 3"/>',home:'<path d="m3 10 9-7 9 7v10H15v-6H9v6H3z"/>',list:'<path d="M8 5h12M8 12h12M8 19h12M3 5h.1M3 12h.1M3 19h.1"/>',share:'<circle cx="18" cy="5" r="3"/><circle cx="5" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8 10 7-4M8 14l7 4"/>',save:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 3v6h8V3M8 21v-7h8v7"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18M7 14h2m3 0h2m3 0h.1M7 17h2m3 0h2"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',plus:'<path d="M12 5v14M5 12h14"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',file:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h4"/>',edit:'<path d="m15 4 5 5M4 20l5-1L21 7a2 2 0 0 0-5-5L4 14z"/>',trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',restore:'<path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',upload:'<path d="M12 16V4m-5 5 5-5 5 5M4 16v5h16v-5"/>',search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.file}</svg>`;
const hydrateIcons=()=>document.querySelectorAll('[data-icon]').forEach(el=>{el.outerHTML=icon(el.dataset.icon)});
const colors=['#327655','#76a68a','#aecbb3','#bb9d65','#709da0','#927fa2','#a77467','#78935f'];
const timeText=m=>m%60?`${Math.floor(m/60)?Math.floor(m/60)+'時間':''}30分`:`${m/60}時間`;
let storageError='',data=fresh(),mode='week',anchor=localDate(),view='dashboard',query='',activityFilter='',showDeleted=false,page=1,editing=null,deleting=null,mergePlan=null,mergeSnapshot='',toastTimer;
try{const raw=localStorage.getItem(KEY);if(raw)data=validate(JSON.parse(raw));}catch{storageError='端末内の記録を読み込めません。既存データを保護するため保存を停止しています。データ共有から救出ファイルを書き出してください。';}
let savedSnapshot=JSON.stringify(data);
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
function persist(next){
  if(storageError)throw Error(storageError);
  const checked=validate(next);
  try{const raw=localStorage.getItem(KEY);const current=raw?JSON.stringify(validate(JSON.parse(raw))):JSON.stringify(fresh());if(current!==savedSnapshot){data=raw?validate(JSON.parse(raw)):fresh();savedSnapshot=JSON.stringify(data);render();throw Error('別のタブで記録が更新されました。内容を確認して、もう一度操作してください。');}localStorage.setItem(KEY,JSON.stringify(checked));}catch(err){if(err.message.includes('別のタブ'))throw err;throw Error('端末に保存できません。空き容量やブラウザーの保存設定を確認してください。入力内容は閉じずに残しています。');}
  data=checked;savedSnapshot=JSON.stringify(data);$('#save-status').innerHTML='<i></i>保存済み';render();
}
function heading(title,subtitle,add=true){return `<header class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div>${add?`<button class="button primary" data-action="add">${icon('plus')}時間を記録</button>`:''}</header>`;}
function emptyTable(message='まだ記録がありません'){return `<div class="empty-state">${icon('file')}<p>${message}</p><small>「時間を記録」から、はじめてみましょう。</small></div>`;}
function recordTable(records){return `<div class="table-wrap"><table><thead><tr><th scope="col">日付</th><th scope="col">活動</th><th scope="col">時間</th><th scope="col" class="note-heading">メモ</th><th scope="col"><span class="visually-hidden">操作</span></th></tr></thead><tbody>${records.map(r=>`<tr><td class="record-date">${r.date.replaceAll('-','/')}</td><td><div class="record-activity"><i></i>${escapeHTML(r.activity)}${r.deleted?'<span class="status-chip">削除済み</span>':''}</div></td><td class="record-time">${timeText(r.minutes)}</td><td class="record-note">${escapeHTML(r.note)||'—'}</td><td class="record-actions">${r.deleted?`<button class="icon-button" data-restore="${escapeHTML(r.id)}" aria-label="${escapeHTML(r.activity)}を復元">${icon('restore')}</button>`:`<button class="icon-button" data-edit="${escapeHTML(r.id)}" aria-label="${escapeHTML(r.activity)}を編集">${icon('edit')}</button><button class="icon-button" data-delete="${escapeHTML(r.id)}" aria-label="${escapeHTML(r.activity)}を削除">${icon('trash')}</button>`}</td></tr>`).join('')}</tbody></table></div>`;}
function chart(records,range){
  let bins=[];
  if(mode==='day'){bins=groups(records);}else{let d=new Date(range.start+'T12:00:00');while(localDate(d)<=range.end){const date=localDate(d);bins.push([date,records.filter(r=>r.date===date).reduce((s,r)=>s+r.minutes,0)]);d.setDate(d.getDate()+1);}}
  if(!bins.length)bins=[['',0]];
  const baseWidth=window.innerWidth<=600?330:560;
  const width=mode==='day'?Math.max(baseWidth,bins.length*65):baseWidth,height=230,left=35,right=12,top=12,bottom=34,plotH=height-top-bottom,plotW=width-left-right;
  const max=Math.max(5,Math.ceil(Math.max(...bins.map(b=>b[1]/60))/5)*5);
  const barSpace=plotW/bins.length;
  let svg=`<svg viewBox="0 0 ${width} ${height}" ${width>baseWidth?`style="min-width:${width}px"`:''} role="img" aria-label="${escapeHTML(mode==='day'?'活動ごとの作業時間':'日付ごとの作業時間')}"><title>${escapeHTML(bins.map(([k,v])=>`${k}: ${timeText(v)}`).join('、'))}</title>`;
  for(let i=0;i<=5;i++){const y=top+i*plotH/5;svg+=`<line x1="${left}" x2="${width-right}" y1="${y}" y2="${y}" stroke="#eaf0ec"/><text x="${left-9}" y="${y+4}" text-anchor="end">${Number((max-i*max/5).toFixed(1))}</text>`;}
  bins.forEach(([label,minutes],i)=>{const x=left+i*barSpace,barH=minutes/60/max*plotH,bw=Math.min(34,barSpace*.54);const date=new Date(label+'T12:00:00');let tick=mode==='day'?(label.length>7?label.slice(0,6)+'…':label):mode==='week'?`${date.getDate()} ${['日','月','火','水','木','金','土'][date.getDay()]}`:`${date.getDate()}`;
    svg+=`<g><title>${escapeHTML(label)}：${timeText(minutes)}</title><rect x="${x+(barSpace-bw)/2}" y="${top+plotH-barH}" width="${bw}" height="${Math.max(0,barH)}" rx="3" fill="${mode==='day'?colors[i%colors.length]:'#327655'}"/>${(mode!=='month'||i%(baseWidth<400?5:3)===0||i===bins.length-1)?`<text x="${x+barSpace/2}" y="${height-10}" text-anchor="middle">${escapeHTML(tick)}</text>`:''}</g>`;
  });
  svg+='</svg>';
  return `<div class="chart-label">（時間）</div><div class="trend">${svg}${!records.length?'<div class="chart-empty"><span>最初の記録から、振り返りをはじめましょう</span></div>':''}</div>`;
}
function breakdown(records){const entries=groups(records),total=entries.reduce((s,e)=>s+e[1],0);let offset=0;const circles=entries.map(([name,v],i)=>{const percent=v/total*100;const c=`<circle cx="50" cy="50" r="40" fill="none" stroke="${colors[i%colors.length]}" stroke-width="13" pathLength="100" stroke-dasharray="${percent} ${100-percent}" stroke-dashoffset="${-offset}"><title>${escapeHTML(name)}：${timeText(v)}</title></circle>`;offset+=percent;return c;}).join('');return `<div class="breakdown-body"><div class="donut-wrap"><svg viewBox="0 0 100 100" role="img" aria-label="活動別の時間配分"><circle cx="50" cy="50" r="40" fill="none" stroke="#e6f0eb" stroke-width="13"/>${circles}</svg><div class="donut-center">${total?`<strong>${total/60}</strong>時間`:'まだ記録が<br>ありません'}</div></div>${total?`<div class="legend">${entries.map(([name,v],i)=>`<div class="legend-row"><i style="background:${colors[i%colors.length]}"></i><span class="activity-name">${escapeHTML(name)}</span><strong>${timeText(v)}</strong><small>${Math.round(v/total*100)}%</small></div>`).join('')}</div>`:'<p class="breakdown-empty">時間を記録すると、<br>ここに活動の内訳が表示されます。</p>'}</div>`;}
function dashboard(){const range=periodRange(mode,anchor),records=inRange(activeRecords(data),range),total=records.reduce((s,r)=>s+r.minutes,0),days=new Set(records.map(r=>r.date)).size;let label=mode==='month'?`${anchor.slice(0,4)}年${Number(anchor.slice(5,7))}月`:mode==='day'?`${anchor.replaceAll('-','/')}（${['日','月','火','水','木','金','土'][new Date(anchor+'T12:00:00').getDay()]}）`:`${range.start.replaceAll('-','/')} – ${range.end.slice(5).replace('-','/')}`;
  return heading('時間を、見えるかたちに。','小さな積み重ねを、次の一歩へ。')+`<div class="toolbar"><div class="segmented" role="group" aria-label="集計期間">${[['day','日'],['week','週'],['month','月']].map(([id,name])=>`<button class="${mode===id?'active':''}" data-mode="${id}" aria-pressed="${mode===id}">${name}</button>`).join('')}</div><div class="date-control"><button class="icon-button" data-shift="-1" aria-label="前の期間">${icon('left')}</button><div class="date-input-wrap">${icon('calendar')}<span>${label}</span><input id="anchor-date" type="date" value="${anchor}" min="1900-01-01" max="2200-12-31" aria-label="表示する日付"></div><button class="icon-button" data-shift="1" aria-label="次の期間">${icon('right')}</button></div><button class="text-button" data-action="today">今日に戻る</button></div><section class="stats" aria-label="期間の集計">${[['clock','合計の時間',total/60,'時間'],['calendar','記録した日数',days,'日'],['grid','活動の種類',groups(records).length,'種類']].map(([ic,l,v,u])=>`<div class="stat">${icon(ic)}<div><div class="stat-label">${l}</div><div class="stat-value"><strong>${v}</strong>${u}</div></div></div>`).join('')}</section><div class="charts"><section class="panel"><div class="panel-heading"><h2>時間の推移</h2><small>${mode==='day'?'活動別':'日別'}</small></div>${chart(records,range)}</section><section class="panel"><div class="panel-heading"><h2>活動の内訳</h2></div>${breakdown(records)}</section></div><section class="panel"><div class="panel-heading"><h2>最近の記録</h2><a class="text-button" href="#records">すべての記録を見る</a></div>${recordTable(sortRecords(records).slice(0,5))}${!records.length?emptyTable():''}</section>`;
}
const sortRecords=records=>[...records].sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt)||a.id.localeCompare(b.id));
function matchingRecords(){return sortRecords(data.records.filter(r=>r.deleted===showDeleted&&(!activityFilter||r.activity===activityFilter)&&(!query||`${r.activity} ${r.note} ${r.date}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))));}
function listResults(){const records=matchingRecords();const pages=Math.max(1,Math.ceil(records.length/25));page=Math.min(page,pages);return `<div class="panel-heading"><h2>${showDeleted?'削除済みの記録':'すべての記録'}</h2><small>${records.length}件 ・ ${timeText(records.reduce((s,r)=>s+r.minutes,0))}</small></div>${recordTable(records.slice((page-1)*25,page*25))}${!records.length?emptyTable(query||activityFilter?'条件に合う記録がありません':showDeleted?'削除済みの記録はありません':'まだ記録がありません'):''}${records.length>25?`<div class="pagination"><button class="button secondary" data-page="-1" ${page<=1?'disabled':''}>前へ</button><span>${page} / ${pages} ページ</span><button class="button secondary" data-page="1" ${page>=pages?'disabled':''}>次へ</button></div>`:''}`;}
function recordsPage(){return heading('記録一覧','積み重ねた時間を、いつでも振り返る。')+`<div class="list-tools"><div class="search">${icon('search')}<input id="record-search" aria-label="記録を検索" type="search" placeholder="活動名・メモ・日付で検索" value="${escapeHTML(query)}"></div><select id="activity-filter" aria-label="活動で絞り込み"><option value="">すべての活動</option>${[...new Set(data.records.map(r=>r.activity))].sort().map(a=>`<option value="${escapeHTML(a)}" ${a===activityFilter?'selected':''}>${escapeHTML(a)}</option>`).join('')}</select><label><input id="deleted-filter" type="checkbox" ${showDeleted?'checked':''}>削除済みを表示</label></div><section class="panel" id="list-results">${listResults()}</section>`;}
function sharePage(){return heading('データ共有','端末が変わっても、あなたの積み重ねはひとつに。',false)+`<div class="share-grid"><section class="panel share-panel"><div class="share-icon">${icon('upload')}</div><h2>ファイルを書き出す</h2><p>この端末のすべての記録を、共有ファイルにまとめます。バックアップにも使えます。</p><div class="download-row"><button class="button primary" data-action="export">${icon('upload')}JSONを書き出す</button><button class="button secondary" data-action="csv">CSV</button></div><small>${activeRecords(data).length}件の記録 / 削除済み ${data.records.filter(r=>r.deleted).length}件${storageError?' / 読み取りエラーあり':''}</small></section><section class="panel share-panel"><div class="share-icon">${icon('download')}</div><h2>ファイルを読み込む</h2><p>もう一方の端末で書き出したJSONを選んでください。内容を確認してから、この端末の記録に統合します。</p><button class="button secondary" data-action="import">${icon('download')}JSONを選ぶ</button><small>同じ記録は重複しません。内容が異なる場合は選べます。</small></section></div><section class="panel help"><h2>PCとAndroidで共有するには</h2><ol><li>記録した端末で「JSONを書き出す」を押します。</li><li>USB・Quick Shareなどで、もう一方の端末にファイルを渡します。</li><li>受け取った端末で「JSONを選ぶ」から読み込み、内容を確認します。</li><li>「統合して保存」を押します。統合後のファイルを元の端末にも読み込むと、両方が揃います。</li></ol><p>自動同期ではありません。CSVは表計算ソフト用で、記録の統合にはJSONを使います。同じ活動を別々に新規登録した記録は別の記録として残ります。</p><details open><summary>Androidで外出先でも使う</summary><p>下の「持ち運び用サイト」を保存し、Androidへ転送してください。AndroidではHTMLファイルを開けるブラウザー（Chromeなど）を指定して開きます。サイト内の「時間を記録」が動き、再度開いて記録が残ることを確認してから使ってください。</p><p>HTMLファイル自体には個人の記録は含まれません。記録の移動には別途JSONが必要です。ファイルの名前・保存場所・使うブラウザーを変えると、別の保存場所になることがあります。</p><button class="button secondary" data-action="portable">${icon('download')}持ち運び用サイトを保存</button><p>Androidの機種やファイルアプリによってはHTMLをブラウザーで開けない場合があります。その場合はHTTPSでサイト本体を配信する方法に切り替えられます。Wi-Fi内のHTTP接続だけでは、外出先のオフライン利用はできません。</p></details><details><summary>保存とバックアップについて</summary><p>記録はこのブラウザー内に保存され、サーバーには送信されません。ブラウザーのデータ削除・シークレットモード・端末の故障で失われることがあります。定期的にJSONを書き出してください。JSONは暗号化されていないため、ご自身が管理できる場所に保存してください。</p><p>削除した記録も、他の端末で復活しないように削除状態を保持しています。「記録一覧」の「削除済みを表示」から復元できます。共有ファイルには削除済みの内容も含まれます。</p>${storageError?'<button class="button secondary" data-action="rescue">読み取れなかった保存データを救出</button>':''}</details></section>`;}
function render(){view=['dashboard','records','share'].includes(location.hash.slice(1))?location.hash.slice(1):'dashboard';document.querySelectorAll('[data-nav]').forEach(el=>{el.classList.toggle('active',el.dataset.nav===view);if(el.dataset.nav===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});$('#main').innerHTML=(storageError?`<div class="notice storage-alert" role="alert">${escapeHTML(storageError)}</div>`:'')+({dashboard,records:recordsPage,share:sharePage}[view])();hydrateIcons();}
function openRecord(id){editing=id?data.records.find(r=>r.id===id):null;const form=$('#record-form');form.reset();form.elements.date.value=editing?.date||localDate();form.elements.activity.value=editing?.activity||'';form.elements.minutes.value=editing?.minutes||30;form.elements.note.value=editing?.note||'';$('#record-title').textContent=editing?'記録を編集':'時間を記録';$('#form-error').textContent='';$('#activities').innerHTML=[...new Set(['ブログ更新','動画編集','SNS更新','リサーチ','学習',...activeRecords(data).map(r=>r.activity)])].map(a=>`<option value="${escapeHTML(a)}">`).join('');$('#record-dialog').showModal();}
function download(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function exportJSON(){download(JSON.stringify({...data,exportedAt:new Date().toISOString()},null,2),`ときの記録_${localDate()}_${Date.now()}.json`,'application/json');toast('共有ファイルの保存を開始しました。');}
function exportCSV(){const cell=v=>'"'+String(v).replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"';const rows=[['日付','活動','時間（分）','メモ'],...sortRecords(activeRecords(data)).map(r=>[r.date,r.activity,r.minutes,r.note])];download('\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n'),`ときの記録_${localDate()}.csv`,'text/csv;charset=utf-8');toast('CSVの保存を開始しました。');}
async function importFile(file){if(!file)return;try{if(file.size>10*1024*1024)throw Error('ファイルが大きすぎます。10MB以下のJSONを選んでください。');const incoming=validate(JSON.parse(await file.text()));mergePlan=planMerge(data,incoming);mergeSnapshot=JSON.stringify(data);$('#merge-error').textContent='';$('#merge-content').innerHTML=`<div class="merge-summary"><span>追加 <strong>${mergePlan.added}件</strong></span><span>更新 <strong>${mergePlan.updated}件</strong></span><span>変更なし <strong>${mergePlan.unchanged}件</strong></span><span>確認が必要 <strong>${mergePlan.conflicts.length}件</strong></span></div><p class="muted">現在の記録は、保存するまで変更されません。削除状態も統合されます。</p>${mergePlan.conflicts.map((c,i)=>`<section class="conflict"><h3>${i+1}. 同じ記録が両方の端末で変更されています</h3><div class="conflict-options">${[['local','この端末を残す'],['incoming','読み込む方を残す']].map(([key,title])=>{const r=c[key];return `<label><input type="radio" name="conflict-${i}" value="${key}" data-conflict-index="${i}"><strong>${title}</strong><span>${r.deleted?'【削除済み】 ':''}${escapeHTML(r.date)} / ${escapeHTML(r.activity)} / ${timeText(r.minutes)}</span><span>${escapeHTML(r.note)||'メモなし'}</span></label>`;}).join('')}</div></section>`).join('')}`;$('#merge-dialog').showModal();}catch(error){toast(error instanceof SyntaxError?'JSONを読み込めません。書き出した共有ファイルを選んでください。':error.message);}finally{$('#import-file').value='';}}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;
  try{
    if(button.dataset.close){$('#'+button.dataset.close).close();return;}
    if(button.dataset.mode){mode=button.dataset.mode;render();return;}
    if(button.dataset.shift){const next=shiftDate(mode,anchor,Number(button.dataset.shift));if(validDate(next)){anchor=next;render();}return;}
    if(button.dataset.page){page+=Number(button.dataset.page);$('#list-results').innerHTML=listResults();return;}
    if(button.dataset.edit){openRecord(button.dataset.edit);return;}
    if(button.dataset.delete){deleting=data.records.find(r=>r.id===button.dataset.delete);$('#delete-description').textContent=`${deleting.date} ・ ${deleting.activity} ・ ${timeText(deleting.minutes)}`;$('#delete-dialog').showModal();return;}
    if(button.dataset.restore){const r=data.records.find(r=>r.id===button.dataset.restore);persist({...data,records:data.records.map(x=>x.id===r.id?revise(r,{...r,deleted:false}):x)});toast('記録を復元しました。');return;}
    const action=button.dataset.action;
    if(action==='add')openRecord();
    if(action==='today'){anchor=localDate();render();}
    if(action==='export')exportJSON();
    if(action==='csv')exportCSV();
    if(action==='import')$('#import-file').click();
    if(action==='portable'){download(portableDocument,'ときの記録.html','text/html;charset=utf-8');toast('サイトの保存を開始しました。記録の移動にはJSONも保存してください。');}
    if(action==='rescue'){download(localStorage.getItem(KEY)||'','ときの記録_救出.txt','text/plain');}
  }catch(error){toast(error.message);}
});
document.addEventListener('change',event=>{if(event.target.id==='anchor-date'&&validDate(event.target.value)){anchor=event.target.value;render();}if(event.target.id==='activity-filter'){activityFilter=event.target.value;page=1;$('#list-results').innerHTML=listResults();}if(event.target.id==='deleted-filter'){showDeleted=event.target.checked;page=1;$('#list-results').innerHTML=listResults();}});
document.addEventListener('input',event=>{if(event.target.id==='record-search'){query=event.target.value;page=1;$('#list-results').innerHTML=listResults();}});
$('#record-form').addEventListener('submit',event=>{event.preventDefault();try{if(editing&&data.records.find(r=>r.id===editing.id)?.rev!==editing.rev)throw Error('この記録は別のタブで更新されました。閉じてから開き直してください。');const f=event.currentTarget;const values={date:f.elements.date.value,activity:f.elements.activity.value.trim(),minutes:Number(f.elements.minutes.value),note:f.elements.note.value,deleted:false};if(!values.activity)throw Error('活動名を入力してください。');const r=revise(editing,values);persist({...data,records:editing?data.records.map(x=>x.id===editing.id?r:x):[...data.records,r]});anchor=r.date;render();$('#record-dialog').close();toast(editing?'記録を更新しました。':'時間を記録しました。');}catch(error){$('#form-error').textContent=error.message;}});
$('#delete-apply').addEventListener('click',()=>{try{if(data.records.find(r=>r.id===deleting.id)?.rev!==deleting.rev)throw Error('この記録は更新されています。閉じてから確認し直してください。');persist({...data,records:data.records.map(r=>r.id===deleting.id?revise(r,{...r,deleted:true}):r)});$('#delete-dialog').close();toast('削除しました。削除済みの一覧から復元できます。');}catch(error){toast(error.message);}});
$('#import-file').addEventListener('change',event=>importFile(event.target.files[0]));
$('#merge-apply').addEventListener('click',()=>{try{if(JSON.stringify(data)!==mergeSnapshot)throw Error('確認中に記録が変更されました。閉じて、ファイルを読み込み直してください。');const choices={};$('#merge-content').querySelectorAll('input:checked').forEach(input=>{choices[mergePlan.conflicts[Number(input.dataset.conflictIndex)].local.id]=input.value;});persist(resolveMerge(mergePlan,choices));$('#merge-dialog').close();toast('記録を統合して保存しました。');}catch(error){$('#merge-error').textContent=error.message;}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(view==='dashboard')render();},150);});
window.addEventListener('storage',event=>{if(event.key!==KEY&&event.key!==null)return;try{data=event.newValue&&event.key===KEY?validate(JSON.parse(event.newValue)):fresh();savedSnapshot=JSON.stringify(data);render();toast('別のタブの変更を反映しました。');}catch{storageError='別のタブの保存データを読み込めません。バックアップを確認してください。';render();}});
$('#record-form').elements.minutes.innerHTML=Array.from({length:48},(_,i)=>`<option value="${(i+1)*30}">${timeText((i+1)*30)}${(i+1)*30<60?'（0.5時間）':''}</option>`).join('');
// Capture the unrendered document: portable downloads must never contain personal data.
const portableDocument='<!doctype html>\n'+document.documentElement.outerHTML;
hydrateIcons();render();
if(['https:','http:'].includes(location.protocol)&&window.isSecureContext&&'serviceWorker' in navigator){const link=document.createElement('link');link.rel='manifest';link.href='./manifest.webmanifest';document.head.append(link);navigator.serviceWorker.register('./sw.js').catch(()=>{});}
